language: cpp
sudo: false

# TODO: When LLVM packages are available again, use these!
matrix:
  include:
    - compiler: gcc
      env:
        - COMPILERC=gcc-4.9
        - COMPILERCXX=g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - libstdc++6-4.9-dbg
            - python3
    - compiler: gcc
      env:
        - COMPILERC=gcc-5
        - COMPILERCXX=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - libstdc++6-4.9-dbg
            - python3
    - compiler: gcc
      env:
        - COMPILERC=gcc-6
        - COMPILERCXX=g++-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - python3
    - compiler: clang
      env:
        - COMPILERC=clang
        - COMPILERCXX=clang++
        - CLANGV=3.6.2
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6-4.9-dbg
            - python3
    - compiler: clang
      env:
        - COMPILERC=clang
        - COMPILERCXX=clang++
        - CLANGV=3.7.1
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6-4.9-dbg
            - python3
    - compiler: clang
      env:
        - COMPILERC=clang
        - COMPILERCXX=clang++
        - CLANGV=3.8.1
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6-4.9-dbg
            - python3
    - compiler: clang
      env:
        - COMPILERC=clang
        - COMPILERCXX=clang++
        - CLANGV=3.9.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6-4.9-dbg
            - python3

# TODO: Eventually cache clang
install:
  - export LLVM_VERSION=3.7.1
  - if [ -n "$CLANGV" ]; then mkdir $HOME/clang+llvm-$CLANGV; fi
  - if [ -n "$CLANGV" ]; then export PATH=$HOME/clang+llvm-$CLANGV/bin:$PATH; fi
  - if [ -n "$CLANGV" ]; then export LD_LIBRARY_PATH=$HOME/clang+llvm-$CLANGV/lib:$LD_LIBRARY_PATH; fi
  - if [ -n "$CLANGV" ]; then wget http://llvm.org/releases/$CLANGV/clang+llvm-$CLANGV-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $HOME/clang+llvm-$CLANGV.tar.xz; fi
  - if [ -n "$CLANGV" ]; then tar xf $HOME/clang+llvm-$CLANGV.tar.xz -C $HOME/clang+llvm-$CLANGV --strip-components 1; fi
  - if [ "$CLANGV" != "$LLVM_VERSION" ]; then mkdir $HOME/clang+llvm-$LLVM_VERSION; fi
  - if [ "$CLANGV" != "$LLVM_VERSION" ]; then wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $HOME/clang+llvm-$LLVM_VERSION.tar.xz; fi
  - if [ "$CLANGV" != "$LLVM_VERSION" ]; then tar xf $HOME/clang+llvm-$LLVM_VERSION.tar.xz -C $HOME/clang+llvm-$LLVM_VERSION --strip-components 1; fi
  - export LLVM_CONFIG=$HOME/clang+llvm-$LLVM_VERSION/bin/llvm-config
  - export CC=$COMPILERC
  - export CXX=$COMPILERCXX
  - $CC --version
  - $CXX --version
  - $LLVM_CONFIG --version
  - $LLVM_CONFIG --cflags
  - $LLVM_CONFIG --cxxflags
  - $LLVM_CONFIG --cppflags
  - $LLVM_CONFIG --ldflags
  - $LLVM_CONFIG --libs
  - $LLVM_CONFIG --system-libs
  - $LLVM_CONFIG --components

script:
  - make -j4 CI=1 LLVM_CONFIG=$LLVM_CONFIG CC=$COMPILERC
  - make test CI=1 LLVM_CONFIG=$LLVM_CONFIG CC=$COMPILERC
