language: cpp
sudo: false
dist: trusty

addons:
  apt:
    sources: &default_srcs
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages: &default_pkgs
      - libglib2.0-dev
      - libstdc++6-4.9-dbg
      - python3
      - llvm-3.8-dev
      - libllvm3.8
      - libdw-dev

matrix:
  include:
    - compiler: gcc
      env:
        - COMPILERC=gcc-4.9
        - COMPILERCXX=g++-4.9
      addons:
        apt:
          sources:
            - *default_srcs
          packages:
            - *default_pkgs
            - gcc-4.9
            - g++-4.9
    - compiler: gcc
      env:
        - COMPILERC=gcc-5
        - COMPILERCXX=g++-5
      addons:
        apt:
          sources:
            - *default_srcs
          packages:
            - *default_pkgs
            - gcc-5
            - g++-5
    - compiler: gcc
      env:
        - COMPILERC=gcc-6
        - COMPILERCXX=g++-6
      addons:
        apt:
          sources:
            - *default_srcs
          packages:
            - *default_pkgs
            - gcc-6
            - g++-6


install:
  - wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build;
  - pip3 install meson


script:
  - meson build -Denable_dwfl=true -enable_llvm=true
  - ninja -C build
  - ninja -C build test
